### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by wwwlqm** [wyuaq/FPN-OAMP-THz-Channel-Estimation#1]
[Errno 2] No such file or directory: './dataset/CSmatrix1024_512_AoSA_angle.mat'
下载完数据集之后显示找不到文件怎么回事

**Comment by wyuaq** [comment]
Dear wwwlqm,

Thanks for your interests in our work. We tried to downloaded the files by ourselves and did not find the mentioned problem. You may try again or generate the datasets by yourself. 

Best Regards,
Wentao
